#' Generate the Posit Connect entry file
#'
#' Writes `inst/app/cliarappak_app.R` -- the file Posit Connect actually
#' executes on every launch, restart, and scale-out of the deployed content.
#' [run_app()]'s arguments only live for the R session that calls it; Connect
#' owns restarting the deployed process on its own schedule, so anything
#' [deploy_app()] wants to survive that has to be written into the code that
#' ships, not just passed once at deploy time. This is a separate, internal
#' function so the file-generation logic can be tested without needing an
#' actual Posit Connect connection.
#'
#' @param path Where to write the entry file.
#' @param ... Named arguments to bake into the generated `run_app(...)` call.
#'   Each is captured with [deparse()], so values must be literal-safe (NULL,
#'   strings, numbers, simple lists) -- this covers every argument
#'   [run_app()] actually takes.
#'
#' @return `path`, invisibly.
#' @noRd
write_deploy_entrypoint <- function(path, ...) {
  run_app_args <- list(...)

  arg_lines <- vapply(
    names(run_app_args),
    function(nm) {
      value_src <- paste(deparse(run_app_args[[nm]]), collapse = "\n")
      paste0("  ", nm, " = ", value_src)
    },
    character(1)
  )

  lines <- c(
    "# Generated by deploy_app() -- do not hand-edit.",
    "# Regenerated fresh on every deploy_app() call; not tracked in git.",
    "library(cliarappak)",
    "",
    "run_app(",
    paste(arg_lines, collapse = ",\n"),
    ")"
  )

  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, path)

  invisible(path)
}

#' Deploy cliarappak to Posit Connect
#'
#' Regenerates the app's Posit Connect entry file with the current
#' [run_app()] arguments baked in, then publishes it with
#' [rsconnect::deployApp()].
#'
#' @param type Character string specifying the deployment target. Must be
#'   one of:
#'   \describe{
#'     \item{\code{"dev"}}{Deploys to the development slot.
#'       Uses the \code{cliarappak_dev_guid} environment variable.}
#'     \item{\code{"prod"}}{Deploys to the production slot.
#'       Uses the \code{cliarappak_prod_guid} environment variable.}
#'   }
#' @param dynamic_year_cutoff Integer year, or `NULL` (default) to derive one
#'   via [resolve_dynamic_year_cutoff()] -- resolved once, here, at deploy
#'   time, and written literally into the generated entry file so it survives
#'   every future restart of the deployed content, not just this deploy.
#' @param onStart,options,enableBookmarking,uiPattern Forwarded to the
#'   generated `run_app()` call. See `?shiny::shinyApp`.
#' @param server Name of the Posit Connect server, as registered with
#'   [rsconnect::addServer()].
#' @param forceUpdate Passed to [rsconnect::deployApp()] -- skips the
#'   interactive confirmation prompt on redeploys.
#' @param ... Further named arguments to bake into the generated `run_app()`
#'   call (forwarded to `golem_opts`, same as extra arguments to
#'   [run_app()] itself).
#'
#' @return Invisibly returns the deployment information from
#'   \code{\link[rsconnect]{deployApp}}.
#'
#' @details
#' This function requires an environment variable set with the Posit Connect
#' application GUID for the chosen `type`:
#' \itemize{
#'   \item \code{cliarappak_dev_guid}
#'   \item \code{cliarappak_prod_guid}
#' }
#' These can be set in your \code{.Renviron} file or through
#' \code{Sys.setenv()}.
#'
#' @examples
#' \dontrun{
#' # Preview a specific data vintage locally first...
#' run_app(dynamic_year_cutoff = 2022)
#'
#' # ...then ship that exact vintage.
#' Sys.setenv(cliarappak_dev_guid = "your-guid-here")
#' deploy_app(dynamic_year_cutoff = 2022, type = "dev")
#'
#' # Production deploy with the auto-derived, current-cycle cutoff.
#' Sys.setenv(cliarappak_prod_guid = "your-guid-here")
#' deploy_app(type = "prod")
#' }
#'
#' @importFrom rsconnect deployApp
#' @export
deploy_app <- function(onStart = NULL,
                       options = list(),
                       enableBookmarking = NULL,
                       uiPattern = "/",
                       dynamic_year_cutoff = NULL,
                       type = c("dev", "prod"),
                       server = "internal-server",
                       forceUpdate = TRUE,
                       ...) {
  type <- match.arg(type)

  guid_var <- paste0("cliarappak_", type, "_guid")
  app_id <- Sys.getenv(guid_var)
  if (!nzchar(app_id)) {
    stop(
      "Environment variable '", guid_var, "' is not set. ",
      "Set it in your .Renviron or via Sys.setenv() before deploying."
    )
  }

  dynamic_year_cutoff <- resolve_dynamic_year_cutoff(dynamic_year_cutoff)

  app_primary_doc <- "inst/app/cliarappak_app.R"
  write_deploy_entrypoint(
    app_primary_doc,
    onStart = onStart,
    options = options,
    enableBookmarking = enableBookmarking,
    uiPattern = uiPattern,
    dynamic_year_cutoff = dynamic_year_cutoff,
    ...
  )

  rsconnect::deployApp(
    appDir        = ".",
    appId         = app_id,
    appPrimaryDoc = app_primary_doc,
    server        = server,
    forceUpdate   = forceUpdate
  )
}
